CREATE TABLE `erwin`.`cars` (`id` INT(11)NOT NULL AUTO_INCREMENT COMMENT 'Primary key auto increment', `brand` VARCHAR(255)NOT NULL COMMENT 'Car brand (Marke)', `type` VARCHAR(255)NOT NULL COMMENT 'Car type/model (Modellbezeichnung)', `body_type` VARCHAR(255)NOT NULL COMMENT 'Car body type (Karosserie/Aufbauart)', `fuel` VARCHAR(255)NOT NULL COMMENT 'Car fuel (Kraftstoff)', `color` VARCHAR(255)NULL DEFAULT NULL COMMENT 'Car body color (Aussenfarbe)', `cubic` INT(11)NULL DEFAULT NULL COMMENT 'Cubic capacity (Hubraum)', `hp` INT(11)NULL DEFAULT NULL COMMENT 'Horse power (PS)', `mileage` DECIMAL(10.1)NULL DEFAULT NULL, `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`))ENGINE = InnoDB; 


INSERT INTO `cars` (`id`, `brand`, `car_type`, `body_type`, `fuel`, `color`, `cubic`, `hp`, `mileage`, `updated`) VALUES (NULL, 'Audi', 'S1', 'Limousine', 'Benzin', 'Black', '2300', '140', '12030', CURRENT_TIMESTAMP);
INSERT INTO `cars` (`id`, `brand`, `car_type`, `body_type`, `fuel`, `color`, `cubic`, `hp`, `mileage`, `updated`) VALUES (NULL, 'Audi', 'S2', 'Kombi', 'Diesel', 'Red', '1800', '140', '12030', CURRENT_TIMESTAMP);
INSERT INTO `cars` (`id`, `brand`, `car_type`, `body_type`, `fuel`, `color`, `cubic`, `hp`, `mileage`, `updated`) VALUES (NULL, 'Audi', 'S3', 'Coupé', 'Benzin', 'Blue', '2500', '140', '12030', CURRENT_TIMESTAMP);
INSERT INTO `cars` (`id`, `brand`, `car_type`, `body_type`, `fuel`, `color`, `cubic`, `hp`, `mileage`, `updated`) VALUES (NULL, 'Audi', 'S4', 'Cabrio', 'Diesel', 'Black', '2700', '140', '12030', CURRENT_TIMESTAMP);
INSERT INTO `cars` (`id`, `brand`, `car_type`, `body_type`, `fuel`, `color`, `cubic`, `hp`, `mileage`, `updated`) VALUES (NULL, 'Audi', 'S5', 'SUV', 'Benzin', 'Orange', '3200', '140', '12030', CURRENT_TIMESTAMP);
INSERT INTO `cars` (`id`, `brand`, `car_type`, `body_type`, `fuel`, `color`, `cubic`, `hp`, `mileage`, `updated`) VALUES (NULL, 'Audi', 'S6', 'Kombi', 'Diesel', 'White', '1600', '140', '12030', CURRENT_TIMESTAMP);
INSERT INTO `cars` (`id`, `brand`, `car_type`, `body_type`, `fuel`, `color`, `cubic`, `hp`, `mileage`, `updated`) VALUES (NULL, 'Audi', 'S7', 'Limousine', 'Benzin', 'Green', '2200', '140', '12030', CURRENT_TIMESTAMP);
INSERT INTO `cars` (`id`, `brand`, `car_type`, `body_type`, `fuel`, `color`, `cubic`, `hp`, `mileage`, `updated`) VALUES (NULL, 'Audi', 'S8', 'Coupé', 'Diesel', 'Black', '2000', '140', '12030', CURRENT_TIMESTAMP);
INSERT INTO `cars` (`id`, `brand`, `car_type`, `body_type`, `fuel`, `color`, `cubic`, `hp`, `mileage`, `updated`) VALUES (NULL, 'Audi', 'RS3', 'Limousine', 'Benzin', 'Yellow', '4000', '140', '12030', CURRENT_TIMESTAMP);
INSERT INTO `cars` (`id`, `brand`, `car_type`, `body_type`, `fuel`, `color`, `cubic`, `hp`, `mileage`, `updated`) VALUES (NULL, 'Audi', 'RS4', 'Kombi', 'Benzin', 'Black', '5000', '140', '12030', CURRENT_TIMESTAMP);